# Question 2
##### Employee Salaries

Data obtained for each employee included current salary(Y), a coded variable indicating highest academic degree obtained (1= bachelor's degree, 2= master's degree, 3= doctoral degree), years of experience since last degree ($X_3$), and the number of persons currently supervised ($X_4$). 

(a) Rewrite the data in the form of ($Y_i$, $x_{i1}$, $x_{i2}$,  $x_{i3}$,  $x_{i4}$) for i=1,...,65. 

In [14]:
salary0 <-read.table(file = "http://www.isye.gatech.edu/~ymei/6414/Handouts/salarydata.csv", sep=",");
salary <- salary0; 
salary$V2 <- I(salary0$V2 ==2);
salary$V3 <- I(salary0$V2 ==3);
salary[,4:5] <- salary0[,3:4];
colnames(salary) <- c("Y", "X1", "X2", "X3", "X4"); 
Y_hat <- salary[,1]; 
salary

Y     X1    X2    X3    X4 
1    58.8 FALSE  TRUE  4.49  0 
2    34.8 FALSE FALSE  2.92  0 
3   163.7 FALSE  TRUE 29.54 42 
4    70.0 FALSE  TRUE  9.92  0 
5    55.5 FALSE  TRUE  0.14  0 
6    85.0  TRUE FALSE 15.96  4 
7    34.0 FALSE FALSE  2.27  0 
8    29.7 FALSE FALSE  1.20  0 
9    56.1  TRUE FALSE  5.33  3 
10   70.6 FALSE  TRUE 15.74  0 
11   74.2 FALSE FALSE 22.46  2 
12   34.1 FALSE FALSE  3.16  0 
13   31.6 FALSE FALSE  2.62  0 
14   65.5 FALSE FALSE 15.06  5 
15   57.2 FALSE  TRUE  2.92  0 
16   60.3 FALSE  TRUE  2.26  0 
17   41.8 FALSE FALSE  9.76  1 
18   76.5 FALSE  TRUE 14.71  4 
19  122.1 FALSE  TRUE 21.76 10 
20   85.9 FALSE  TRUE 15.63  8 
21   55.9 FALSE  TRUE  1.17  0 
22   44.3  TRUE FALSE  2.33  0 
23   79.9 FALSE  TRUE 17.10 18 
24   58.5  TRUE FALSE  7.45  0 
25   57.3 FALSE  TRUE  4.55  0 
26   61.0  TRUE FALSE 14.39  8 
27   52.2  TRUE FALSE  5.78  3 
28   45.7  TRUE FALSE  2.08  0 
29   44.8  TRUE FALSE  1.44  0 
30   39.1  TRUE FALSE  1.00  0 
... ...   ...   ...   ...   ...
36   40.9  TRUE FALSE  1.02  0 
37   57.7 FALSE FALSE 10.14  5 
38   95.5 FALSE  TRUE 26.53  8 
39   34.9 FALSE FALSE  6.49  0 
40   66.6  TRUE FALSE 13.97  7 
41   30.0 FALSE FALSE  4.18  0 
42   64.9 FALSE  TRUE 12.88  6 
43  151.2  TRUE FALSE 16.01 28 
44   72.4  TRUE FALSE 11.13  6 
45   41.8  TRUE FALSE  0.71  0 
46   57.8 FALSE  TRUE  1.55  0 
47   72.7 FALSE  TRUE  3.92  0 
48   36.1 FALSE FALSE  4.37  0 
49   39.8  TRUE FALSE  0.79  0 
50   29.0 FALSE FALSE  0.65  0 
51   40.4  TRUE FALSE  0.69  0 
52   40.7  TRUE FALSE  1.09  0 
53   41.7  TRUE FALSE  1.58  0 
54   97.2 FALSE  TRUE 10.89  8 
55   85.3  TRUE FALSE 21.08  0 
56   42.6  TRUE FALSE  7.00  0 
57   39.1 FALSE FALSE  4.09  0 
58   46.6  TRUE FALSE  8.86  0 
59   53.9  TRUE FALSE 11.05  6 
60   87.4 FALSE  TRUE  2.37 13 
61   81.7 FALSE  TRUE  6.37  0 
62   42.5 FALSE FALSE  8.00  0 
63   40.0  TRUE FALSE  0.44  0 
64   60.5 FALSE  TRUE  2.10  0 
65  104.8 FALSE  TRUE 19.81 24

(b) Regress Y on $X_1$, $X_2$, $X_3$, $X_4$ (all at once), using first-order model and ordinary least squares. Obtain the residuals, and plot them against $\hat{Y}$. What does the residual plot mean?

$\textbf{Obtaining Residuals: }$

In [4]:
fm1 <- lm (salary[,1] ~ salary[,2]+salary[,3]+salary[,4]+salary[,5])
fm1
resid(fm1)


Call:
lm(formula = salary[, 1] ~ salary[, 2] + salary[, 3] + salary[, 
    4] + salary[, 5])

Coefficients:
    (Intercept)  salary[, 2]TRUE  salary[, 3]TRUE      salary[, 4]  
         31.471           10.812           22.631            1.258  
    salary[, 5]  
          1.852  


1           2           3           4           5           6 
 -0.9511354  -0.3451532  -5.3642878   3.4172502   1.2217049  15.2277038 
          7           8           9          10          11          12 
 -0.3273725  -3.2811796   1.5538770  -3.3050327  10.7664740  -1.3471030 
         13          14          15          16          17          18 
 -3.1677159   5.8196545  -0.5758804   3.3544816  -3.8030357  -3.5184163 
         19          20          21          22          23          24 
 22.0979307  -2.6851421   0.3258370  -0.9148117 -29.0577135   6.8435923 
         25          26          27          28          29          30 
 -2.5266228 -14.2062928  -2.9122789   0.7997193   0.7049188  -4.4415065 
         31          32          33          34          35          36 
  3.3070053 -18.2771109   2.1995343   3.6550793   5.2919201  -2.6666690 
         37          38          39          40          41          42 
  4.2096256  -6.7986960  -4.7366566  -6.2255677  -6.7303897 -16.5206748 
         43          44          45          46          47          48 
 36.9092884   4.9998179  -1.3766505   1.7477498  13.6659954  -0.8694333 
         49          50          51          52          53          54 
 -3.4773005  -3.2892112  -2.7514880  -2.9547377  -2.5712186  14.5783666 
         55          56          57          58          59          60 
 16.4953593  -8.4902518   2.4828415  -6.8303628 -13.3995321   6.2360205 
         61          62          63          64          65 
 19.5835911   0.9635758  -2.8369570   3.7557815 -18.6811074

$\textbf{Plotting residuals:}$

In [13]:
plot(Y_hat, resid(fm1),xlab="Current Salary(Y_hat)", ylab="Residual")

What does this residual plot Suggest????? 

(c) Plot the absolute residuals against $X_3$ and against $X_4$. What do these plots suggest about the relation between the standard deviation of the error term and $X_3$ and $X_4$? 

In [18]:
plot (salary[,4], abs(resid(fm1)), xlab="Years of experience since last degree",ylab="Absolute residual" )
plot (salary[,5], abs(resid(fm1)), xlab="Number of persons currently supervised",ylab="Absolute residual" )

Write about standard deviation of error term............

(d) Estimate the standard deviation function by regressing the absolute residuals against $X_3$ and $X_4$ (in first-order form), and then calculate the estimated weight for each case using $w_{i} = 1/{\hat{s_i}}^2$, where $\hat{s_i}$ is fitted value for the absolute residuals. Report value of $w_i$ for four i=1,2,64,65. 

$\textbf{Standard deviation function for |residual| against $X_3$}$

In [23]:
reslm <- lm(abs (resid(fm1)) ~ salary[,4]); 
reslm
S1= 1.9603 + 0.5741 * salary[,4]; 


Call:
lm(formula = abs(resid(fm1)) ~ salary[, 4])

Coefficients:
(Intercept)  salary[, 4]  
     1.9603       0.5741  


The standard deviation function, $S_1$ (absolute residuals, $X_3$)= $\textbf{1.9603 + 0.5741 $X_3$}$


Obtaining the weights: $w_{i} = 1/{\hat{s_i}}^2$

In [26]:
w= 1/ S1^2;
lm2 <- lm(Y_hat ~ salary[,4], weight=w);
summary(lm2)


Call:
lm(formula = Y_hat ~ salary[, 4], weights = w)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-5.8396 -1.7067 -0.4069  0.8953 12.2999 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  41.1426     2.0367  20.200  < 2e-16 ***
salary[, 4]   2.2828     0.4759   4.797 1.02e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.224 on 63 degrees of freedom
Multiple R-squared:  0.2676,	Adjusted R-squared:  0.2559 
F-statistic: 23.01 on 1 and 63 DF,  p-value: 1.024e-05


In [29]:
weight1 <- 1.9603 + 0.5741 * salary[1,4]
weight2 <- 1.9603 + 0.5741 * salary[2,4]
weight64 <- 1.9603 + 0.5741 * salary[64,4]
weight65 <- 1.9603 + 0.5741 * salary[65,4]
weight1
weight2
weight64
weight65

[1] 4.538009

[1] 3.636672

[1] 3.16591

[1] 13.33322

$w_1$ = 4.538009
$w_2$ = 3.636672
$w_{64}$ = 3.16591
$w_{65}$ = 13.333221

$\textbf{Standard deviation function for |residual| against $X_4$}$

In [32]:
reslm2 <- lm(abs (resid(fm1)) ~ salary[,5]); 
reslm2
S2= 4.7422 + 0.5187 * salary[,5]; 


Call:
lm(formula = abs(resid(fm1)) ~ salary[, 5])

Coefficients:
(Intercept)  salary[, 5]  
     4.7422       0.5187  


The standard deviation function, $S_2$ (absolute residuals, $X_3$)= $\textbf{4.7422 + 0.5187 $X_4$}$

In [34]:
w_k= 1/ S2^2;
lm3 <- lm(Y_hat ~ salary[,5], weight=w_k);
summary(lm3)


Call:
lm(formula = Y_hat ~ salary[, 5], weights = w_k)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-4.0943 -1.7521 -0.5906  1.8734  7.7778 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  48.4161     1.8364  26.365  < 2e-16 ***
salary[, 5]   3.5204     0.6307   5.582 5.38e-07 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.606 on 63 degrees of freedom
Multiple R-squared:  0.3309,	Adjusted R-squared:  0.3203 
F-statistic: 31.16 on 1 and 63 DF,  p-value: 5.384e-07


In [35]:
weight_1 <- 4.7422 + 0.5187 * salary[1,5]; 
weight_2 <- 4.7422 + 0.5187 * salary[2,5]; 
weight_64 <- 4.7422 + 0.5187 * salary[64,5]; 
weight_65 <- 4.7422 + 0.5187 * salary[65,5]; 
weight_1
weight_2
weight_64
weight_65

[1] 4.7422

[1] 4.7422

[1] 4.7422

[1] 17.191

$w_1$ = 4.7422 
$w_2$ = 4.7422 
$w_{64}$ = 4.7422 
$w_{65}$ = 17.191 

(e) Using the estimated weights, obtain the weighted least sqaures fit of the regression model. Are the weighted least sqaures estimates of the regression coefficients similar to the ones obtained with ordinary least squares in part (b)? 